Update usage_and_examples.md
emdgroup/foundry-dev-tools pull request #12
Opened 2023-04-06 12:08 UTC by cheTesta

# Summary

Updated a small typo in the documentation page.

# Checklist

- [ ] You agree with our [CLA](https://gist.githubusercontent.com/emdgroup-admin/16cc45ea4315c2ef29eb9d9afc36fcf5/raw/abb9c91f15278a62b9ac3e66144bcd27fa9485c2/CLA.md)
- [ ] Included tests (or is not applicable).
- [ ] Updated [documentation](https://emdgroup.github.io/foundry-dev-tools/) (or is not applicable).
- [ ] Used [pre-commit hooks](https://emdgroup.github.io/foundry-dev-tools/develop.html#pre-commit-hooks-formatting) to format and lint the code.

2023-04-06 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/emdgroup/foundry-dev-tools?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/emdgroup/foundry-dev-tools?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/emdgroup/foundry-dev-tools?pullRequest=12) it.</sub>

2023-04-12 18:23 UTC, nicornk requested changes
Small changes.

2023-04-12 18:23 UTC, nicornk commented on docs/installation.md
> +[python environment]: https://docs.python.org/3/library/venv.html
Can you revert your changes to this file?

2023-04-12 18:23 UTC, nicornk commented on docs/usage_and_examples.md
> +```
Can you revert the line ending change?

2023-04-12 18:23 UTC, nicornk commented on docs/usage_and_examples.md
> ++      version=os.getenv('PKG_VERSION', 'your-package-version'),
Thanks for the contribution! Good catch.

2023-04-13 13:34 UTC, jonas-w approved these changes
Thanks for catching this copy paste error, I modified your fork and removed the accidental changes.

2023-04-13 13:34 UTC, jonas-w commented on docs/installation.md
this file seems to be edited by accident?

2023-04-13 13:36 UTC, nicornk approved these changes

2023-04-13 13:37 UTC, merged

2023-04-13 13:39 UTC, cheTesta commented
Thanks @jonas-w  @nicornk .